export default function Rarity() {
    return (
<div className="w-full min-h-screen flex justify-center items-center py-16" style={{backgroundColor:'#0736a4', backgroundImage:'url(https://cdn.prod.website-files.com/6849a9348eca7a8dbfd29a2d/6849a9358eca7a8dbfd29b00_diagrams.png)'}}>
<div className="relative bg-white rounded-2xl border-8 border-black shadow-xl p-10 pt-8 w-full max-w-3xl flex flex-col items-center">
  <h2 className="text-4xl font-extrabold text-black text-center leading-tight mb-2 tracking-tight">RARITY</h2>
  <p className="text-xs text-black font-mono text-center mb-6 mt-2 max-w-xl font-semibold">
    Each NFT is algorithmically generated by combining 170+ unique traits with varying rarity across categories.
  </p>
  <div className="grid grid-cols-2 gap-8 w-full mb-6">
    <div className="flex flex-col items-start">
      <div className="font-bold text-lg mb-2 text-black">Types</div>
      <div className="flex flex-col gap-1 mb-4">
        <div className="flex justify-between text-black font-semibold"><span>9,999</span><span>Total Robots</span></div>
        <div className="flex justify-between text-black font-semibold"><span>Common</span><span>Robotos</span></div>
        <div className="flex justify-between bg-blue-100 px-2 rounded text-black font-semibold"><span>Less Common</span><span>Helmetos</span></div>
        <div className="flex justify-between text-black font-semibold"><span>Rare</span><span>Computos</span></div>
        <div className="flex justify-between bg-blue-100 px-2 rounded text-black font-semibold"><span>Super Rare</span><span>Cyborgos</span></div>
      </div>
      <img src="https://cdn.prod.website-files.com/6849a9348eca7a8dbfd29a2d/6849a9358eca7a8dbfd29b11_rarity.svg" alt="rarity illustration" className="mt-6 w-64 h-auto mx-auto border rounded-lg" />
    </div>
    <div>
      <div className="font-bold text-lg mb-2 text-black">Variations</div>
      <div className="flex flex-col gap-1">
        <div className="flex justify-between bg-blue-100 px-2 rounded text-black font-semibold"><span>38</span><span>Head Tops</span></div>
        <div className="flex justify-between text-black font-semibold"><span>32</span><span>Eyes</span></div>
        <div className="flex justify-between bg-blue-100 px-2 rounded text-black font-semibold"><span>18</span><span>Helmets</span></div>
        <div className="flex justify-between text-black font-semibold"><span>16</span><span>Mouth</span></div>
        <div className="flex justify-between text-black font-semibold"><span>18</span><span>Ears</span></div>
        <div className="flex justify-between text-black font-semibold"><span>12</span><span>Arms</span></div>
        <div className="flex justify-between text-black font-semibold"><span>10</span><span>Chassis Colors</span></div>
        <div className="flex justify-between text-black font-semibold"><span>8</span><span>Backpacks</span></div>
        <div className="flex justify-between text-black font-semibold"><span>6</span><span>Computo Heads</span></div>
        <div className="flex justify-between text-black font-semibold"><span>6</span><span>Chest Screens</span></div>
        <div className="flex justify-between bg-blue-100 px-2 rounded text-black font-semibold"><span>5</span><span>Bodies</span></div>
        <div className="flex justify-between text-black font-semibold"><span>4</span><span>Head Types</span></div>
        <div className="flex justify-between text-black font-semibold"><span>4</span><span>Human Faces</span></div>
      </div>
    </div>
  </div>
  <div className="flex flex-row flex-wrap justify-center items-center gap-2 mt-4">
    <img src="https://robohash.org/robot1.png?set=set1" alt="robot1" className="w-20 h-20 rounded-lg border-2 border-black bg-white" />
    <img src="https://robohash.org/robot2.png?set=set1" alt="robot2" className="w-20 h-20 rounded-lg border-2 border-black bg-white" />
    <img src="https://robohash.org/robot3.png?set=set1" alt="robot3" className="w-20 h-20 rounded-lg border-2 border-black bg-white" />
    <img src="https://robohash.org/robot4.png?set=set1" alt="robot4" className="w-20 h-20 rounded-lg border-2 border-black bg-white" />
    <img src="https://robohash.org/robot5.png?set=set1" alt="robot5" className="w-20 h-20 rounded-lg border-2 border-black bg-white" />
  </div>
</div>
</div>
    );
}